version: '3.8'

services:
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    restart: unless-stopped
    ports:
      - "1884:1884"       # MQTT
      - "9001:9001"       # WebSocket (optional)
    volumes:
      - ./mosquitto:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log

  nginx:
    image: nginx:latest
    ports:
      - "80:80"  
    volumes:
      - ./html:/usr/share/nginx/html:ro
    restart: always






